/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Audit
         * @description Query audit rows, newest first. Pass next_cursor back as ``cursor`` for older rows.
         */
        get: operations["query_audit_v1_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List users ordered by id. Pass next_cursor back as ``cursor`` for the next page.
         */
        get: operations["list_users_v1_admin_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create a user with one or more roles.
         */
        post: operations["create_user_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Update a user's display name, status, roles or password.
         */
        patch: operations["update_user_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange email and password for a bearer token.
         */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Record the logout. Tokens are stateless, so the client discards its token.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated caller with roles loaded from the database.
         */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/miss-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Miss Report
         * @description Open a miss_report review task holding the query, filters and as-on date.
         */
        post: operations["create_miss_report_v1_miss_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List documents, newest first. Filter by type, review state, or a title or ID prefix.
         */
        get: operations["list_documents_v1_platform_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description One document: metadata, typed-table row, versions, sources, status history, open tasks.
         */
        get: operations["get_document_v1_platform_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Document
         * @description Edit metadata fields (queued for the worker) and/or set the status (written here).
         */
        patch: operations["patch_document_v1_platform_documents__document_id__patch"];
        trace?: never;
    };
    "/v1/platform/documents/{document_id}/versions/{version_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Blocks
         * @description Blocks of one version in seq order. Optionally one page, and keyset-paged by seq.
         */
        get: operations["list_blocks_v1_platform_documents__document_id__versions__version_id__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/documents/{document_id}/versions/{version_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pages
         * @description Extraction outcome for every page of one version.
         */
        get: operations["list_pages_v1_platform_documents__document_id__versions__version_id__pages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/documents/{document_id}/versions/{version_id}/pages/{page_no}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page Image
         * @description Page n of a PDF version as a PNG at 110 dpi. Cached in the object store by raw hash.
         */
        get: operations["page_image_v1_platform_documents__document_id__versions__version_id__pages__page_no__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/documents/{document_id}/versions/{version_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw File
         * @description The original file as it was received, as an attachment.
         */
        get: operations["raw_file_v1_platform_documents__document_id__versions__version_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/ingestion/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Ingestion metrics from the views, plus the alerts that are firing now.
         */
        get: operations["get_dashboard_v1_platform_ingestion_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/ingestion/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return the stage, status and error (if any) of one ingestion job.
         */
        get: operations["get_job_v1_platform_ingestion_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/ingestion/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Manual
         * @description Upload a PDF or HTML file for loading. It is stored once, then the worker takes over.
         */
        post: operations["submit_manual_v1_platform_ingestion_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/ingestion/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Url
         * @description Queue a document for loading by URL. The worker fetches it and writes the records.
         */
        post: operations["submit_url_v1_platform_ingestion_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Re-queue a failed ingestion job for its stage. Anything else is 409.
         */
        post: operations["retry_job_v1_platform_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/review-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List review tasks. Defaults to open and in-review tasks, ordered by priority then age.
         */
        get: operations["list_tasks_v1_platform_review_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/review-tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description Return one task with its context: the document, version, problem pages and duplicate.
         */
        get: operations["get_task_v1_platform_review_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/review-tasks/{task_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Task
         * @description Assign a task to a content editor or platform admin, or unassign it with null.
         */
        post: operations["assign_task_v1_platform_review_tasks__task_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/review-tasks/{task_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Task
         * @description Record a decision: approve, edit_approve, reject or needs_info.
         *
         *     The proposal in ``resolution`` is never changed. The decision is stored next to it.
         */
        post: operations["decide_task_v1_platform_review_tasks__task_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Every configured source with its enable flag, cadence and last success.
         */
        get: operations["list_sources_v1_platform_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/platform/sources/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description Enable or disable a source, and set its expected cadence. Audited as source.update.
         */
        patch: operations["update_source_v1_platform_sources__code__patch"];
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Get API version and corpus version.
         */
        get: operations["version_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Alert
         * @description A threshold that is breached now.
         */
        Alert: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "failure_rate" | "freshness_p95" | "stale_source" | "overdue_review" | "queue_lag";
            /** Message */
            message: string;
            /** Subject */
            subject: string | null;
        };
        /**
         * AssignBody
         * @description Body of POST /{id}/assign. ``null`` unassigns; ``me`` assigns the caller.
         */
        AssignBody: {
            /** Assignee Id */
            assignee_id: string | "me" | null;
        };
        /**
         * AuditItem
         * @description One audit row as returned by the admin API.
         */
        AuditItem: {
            /** Action */
            action: string;
            /** Actor Role */
            actor_role: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip */
            ip: string | null;
            /** Object Id */
            object_id: string | null;
            /** Object Type */
            object_type: string | null;
            /** Request Id */
            request_id: string | null;
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * AuditList
         * @description One page of audit rows, newest first.
         */
        AuditList: {
            /** Items */
            items: components["schemas"]["AuditItem"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /**
         * BlockItem
         * @description A block on a problem page.
         */
        BlockItem: {
            /** Bbox */
            bbox: unknown;
            /** Page */
            page: number | null;
            /** Seq */
            seq: number;
            /** Structure Path */
            structure_path: string | null;
            /** Text */
            text: string;
        };
        /**
         * BlockOut
         * @description One block of a version, in reading order.
         */
        BlockOut: {
            /** Bbox */
            bbox: unknown;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Boilerplate */
            is_boilerplate: boolean;
            /** Kind */
            kind: string;
            /** Lang */
            lang: string | null;
            /** Page */
            page: number | null;
            /** Para Label */
            para_label: string | null;
            /** Seq */
            seq: number;
            /** Structure Path */
            structure_path: string | null;
            /** Text */
            text: string;
        };
        /**
         * BlockPage
         * @description A page of blocks. next_cursor is the last seq; pass it back as ``after``.
         */
        BlockPage: {
            /** Items */
            items: components["schemas"]["BlockOut"][];
            /** Next Cursor */
            next_cursor: number | null;
        };
        /** Body_submit_manual_v1_platform_ingestion_manual_post */
        Body_submit_manual_v1_platform_ingestion_manual_post: {
            /** Case Number */
            case_number?: string | null;
            /** Circular A */
            circular_a?: string | null;
            /** Circular B */
            circular_b?: string | null;
            /** Court Code */
            court_code?: string | null;
            /** Decision Date */
            decision_date?: string | null;
            /** Doc Type */
            doc_type: string;
            /** File */
            file: string;
            /** Number */
            number?: string | null;
            /** Series */
            series?: string | null;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
            /** Year */
            year?: string | null;
        };
        /**
         * CrossCheckRow
         * @description Pages where the two text engines were compared, and how many disagree by over 5%.
         */
        CrossCheckRow: {
            /** Compared Pages */
            compared_pages: number;
            /** Disagreements */
            disagreements: number;
        };
        /**
         * DailyRow
         * @description Jobs discovered on one day for one source, by status.
         */
        DailyRow: {
            /**
             * Day
             * Format: date-time
             */
            day: string;
            /** Discovered */
            discovered: number;
            /** Done */
            done: number;
            /** Failed */
            failed: number;
            /** Queued */
            queued: number;
            /** Running */
            running: number;
            /** Skipped */
            skipped: number;
            /** Source Code */
            source_code: string | null;
        };
        /**
         * Dashboard
         * @description Everything the ingestion dashboard shows, and the alerts that are firing.
         */
        Dashboard: {
            /** Alerts */
            alerts: components["schemas"]["Alert"][];
            cross_check_disagreements: components["schemas"]["CrossCheckRow"];
            /** Daily */
            daily: components["schemas"]["DailyRow"][];
            /** Freshness */
            freshness: components["schemas"]["FreshnessRow"][];
            /** Numbering Gaps */
            numbering_gaps: {
                [key: string]: string;
            };
            /** Page Accounting */
            page_accounting: components["schemas"]["PageAccountingRow"][];
            /** Queue Lag */
            queue_lag: components["schemas"]["QueueLagRow"][];
            /** Review Queue */
            review_queue: components["schemas"]["ReviewQueueRow"][];
            /** Source Health */
            source_health: components["schemas"]["SourceHealthRow"][];
        };
        /**
         * DecisionBody
         * @description Body of POST /{id}/decision.
         */
        DecisionBody: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "edit_approve" | "reject" | "needs_info";
            /** Fields */
            fields?: {
                [key: string]: unknown;
            } | null;
            /** Note */
            note?: string | null;
        };
        /**
         * DocumentDetail
         * @description A document with its metadata, typed-table row, versions, sources and open tasks.
         */
        DocumentDetail: {
            /** Authority Rank */
            authority_rank: number;
            /** Bench */
            bench: string | null;
            /** Canonical Id */
            canonical_id: string;
            /** Court */
            court: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Version Id */
            current_version_id: string | null;
            /** Doc Date */
            doc_date: string | null;
            /** Doc Type */
            doc_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** In Force Date */
            in_force_date: string | null;
            /** Issuing Authority */
            issuing_authority: string | null;
            /** Meta Confidence */
            meta_confidence: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Number */
            number: string | null;
            /** Open Review Task Ids */
            open_review_task_ids: string[];
            /** Review State */
            review_state: string;
            /** Series */
            series: string | null;
            /** Sources */
            sources: components["schemas"]["SourceLinkOut"][];
            /** Status */
            status: string;
            /** Status History */
            status_history: components["schemas"]["StatusEvent"][];
            /** Title */
            title: string;
            /** Typed Row */
            typed_row: {
                [key: string]: unknown;
            } | null;
            /** Typed Table */
            typed_table: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Versions */
            versions: components["schemas"]["VersionOut"][];
        };
        /**
         * DocumentList
         * @description A page of documents. next_cursor is passed back as ``cursor``; null on the last page.
         */
        DocumentList: {
            /** Items */
            items: components["schemas"]["app__routers__platform_documents__DocumentSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * DocumentPatch
         * @description Body of PATCH /{id}: metadata fields, and optionally a status change.
         */
        DocumentPatch: {
            /** Fields */
            fields?: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Status */
            status?: ("in_force" | "amended" | "superseded" | "rescinded" | "struck_down" | "stayed") | null;
            /** Status Valid From */
            status_valid_from?: string | null;
        };
        /**
         * FreshnessRow
         * @description Hours from discovery to publication. source_code is null for the overall row.
         */
        FreshnessRow: {
            /** P50 Hours */
            p50_hours: number | null;
            /** P95 Hours */
            p95_hours: number | null;
            /** Samples */
            samples: number;
            /** Source Code */
            source_code: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionJobStatus
         * @description Response of GET /jobs/{id}.
         */
        IngestionJobStatus: {
            /** Attempt */
            attempt: number;
            /** Document Id */
            document_id: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Url */
            url: string | null;
        };
        /**
         * LoginRequest
         * @description Email and password to exchange for a token.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description The authenticated caller.
         */
        MeResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Roles */
            roles: string[];
            /** Tenant Id */
            tenant_id: string | null;
        };
        /**
         * MissReportCreated
         * @description The new review task.
         */
        MissReportCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * MissReportIn
         * @description What the user searched for, and what they expected to find.
         */
        MissReportIn: {
            /** As On */
            as_on?: string | null;
            /** Expected */
            expected?: string | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            };
            /** Query */
            query: string;
        };
        /**
         * PageAccountingRow
         * @description Page extraction outcomes by method and status.
         */
        PageAccountingRow: {
            /** Flagged Pages */
            flagged_pages: number;
            /** Method */
            method: string;
            /** Pages */
            pages: number;
            /** Pages Last 30D */
            pages_last_30d: number;
            /** Status */
            status: string;
        };
        /**
         * PageList
         * @description Page accounting for one version.
         */
        PageList: {
            /** Items */
            items: components["schemas"]["PageOut"][];
        };
        /**
         * PageOut
         * @description Extraction outcome for one page.
         */
        PageOut: {
            /** Chars Engine A */
            chars_engine_a: number | null;
            /** Chars Engine B */
            chars_engine_b: number | null;
            /** Flagged */
            flagged: boolean;
            /** Garble Score */
            garble_score: number | null;
            /** Method */
            method: string;
            /** Ocr Conf */
            ocr_conf: number | null;
            /** Page No */
            page_no: number;
            /** Status */
            status: string;
        };
        /**
         * PatchAccepted
         * @description What the PATCH did. Field edits are queued; status changes are written at once.
         */
        PatchAccepted: {
            /** Queued */
            queued: boolean;
            /** Status Changed */
            status_changed: boolean;
        };
        /**
         * ProblemPage
         * @description A page that failed extraction or was flagged, with its first blocks and page text.
         */
        ProblemPage: {
            /** Blocks */
            blocks: components["schemas"]["BlockItem"][];
            /** Flagged */
            flagged: boolean;
            /** Method */
            method: string;
            /** Page No */
            page_no: number;
            /** Page Text */
            page_text: string | null;
            /** Page Text Truncated */
            page_text_truncated: boolean;
            /** Status */
            status: string;
        };
        /**
         * QueueLagRow
         * @description Queued jobs per queue, and how long the oldest has been due.
         */
        QueueLagRow: {
            /** Lag Minutes */
            lag_minutes: number;
            /** Oldest Created At */
            oldest_created_at: string | null;
            /** Oldest Run After */
            oldest_run_after: string | null;
            /** Queue */
            queue: string;
            /** Queued */
            queued: number;
        };
        /**
         * RetryAccepted
         * @description The job is queued again on this queue.
         */
        RetryAccepted: {
            /**
             * Ingestion Job Id
             * Format: uuid
             */
            ingestion_job_id: string;
            /** Queue */
            queue: string;
        };
        /**
         * ReviewQueueRow
         * @description Open review tasks by kind and status.
         */
        ReviewQueueRow: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
            /** Oldest Opened At */
            oldest_opened_at: string | null;
            /** Overdue Count */
            overdue_count: number;
            /** Status */
            status: string;
        };
        /**
         * ReviewTaskDetail
         * @description A review task with its context.
         */
        ReviewTaskDetail: {
            /** Assignee Id */
            assignee_id: string | null;
            /** Assignee Name */
            assignee_name: string | null;
            /** Closed At */
            closed_at: string | null;
            document?: components["schemas"]["app__routers__review_tasks__DocumentSummary"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            near_duplicate_of?: components["schemas"]["app__routers__review_tasks__DocumentSummary"] | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Priority */
            priority: number;
            /** Problem Pages */
            problem_pages?: components["schemas"]["ProblemPage"][];
            /** Resolution */
            resolution: {
                [key: string]: unknown;
            } | null;
            /** Sla Due At */
            sla_due_at: string | null;
            /** Status */
            status: string;
            /** Subject Id */
            subject_id: string | null;
            /** Subject Type */
            subject_type: string;
            /** Title */
            title: string | null;
            version?: components["schemas"]["VersionSummary"] | null;
        };
        /**
         * ReviewTaskItem
         * @description A review task as listed.
         */
        ReviewTaskItem: {
            /** Assignee Id */
            assignee_id: string | null;
            /** Assignee Name */
            assignee_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Priority */
            priority: number;
            /** Sla Due At */
            sla_due_at: string | null;
            /** Status */
            status: string;
            /** Subject Id */
            subject_id: string | null;
            /** Subject Type */
            subject_type: string;
            /** Title */
            title: string | null;
        };
        /**
         * ReviewTaskList
         * @description One page of review tasks, in queue order.
         */
        ReviewTaskList: {
            /** Items */
            items: components["schemas"]["ReviewTaskItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /**
         * ReviewTaskUpdate
         * @description A task after an assign or decision, with any notices about what was not done.
         */
        ReviewTaskUpdate: {
            /** Assignee Id */
            assignee_id: string | null;
            /** Assignee Name */
            assignee_name: string | null;
            /** Closed At */
            closed_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Notices */
            notices?: string[];
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Priority */
            priority: number;
            /** Resolution */
            resolution: {
                [key: string]: unknown;
            } | null;
            /** Sla Due At */
            sla_due_at: string | null;
            /** Status */
            status: string;
            /** Subject Id */
            subject_id: string | null;
            /** Subject Type */
            subject_type: string;
            /** Title */
            title: string | null;
        };
        /**
         * SourceHealthRow
         * @description A source's last new document against its expected cadence.
         */
        SourceHealthRow: {
            /** Code */
            code: string;
            /** Enabled */
            enabled: boolean;
            /** Expected Cadence Hours */
            expected_cadence_hours: number | null;
            /** Hours Since New Doc */
            hours_since_new_doc: number | null;
            /** Last New Doc At */
            last_new_doc_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Stale */
            stale: boolean;
        };
        /**
         * SourceLinkOut
         * @description A URL a document was seen at, with the source it came from.
         */
        SourceLinkOut: {
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Source Code */
            source_code: string;
            /** Url */
            url: string;
        };
        /**
         * SourceList
         * @description Every source in config, then any row in the table that config does not name.
         */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceOut"][];
        };
        /**
         * SourceOut
         * @description A source: config fields merged with the run-time row when there is one.
         */
        SourceOut: {
            /** Allowed Hosts */
            allowed_hosts: string[];
            /** Code */
            code: string;
            /** Config Enabled */
            config_enabled: boolean | null;
            /** Description */
            description: string | null;
            /** Enabled */
            enabled: boolean;
            /** Expected Cadence Hours */
            expected_cadence_hours: number | null;
            /** Health */
            health: string | null;
            /** In Config */
            in_config: boolean;
            /** Kind */
            kind: string;
            /** Last New Doc At */
            last_new_doc_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Release */
            release: string | null;
        };
        /**
         * SourceUpdate
         * @description Body of PATCH /{code}. At least one field must be set.
         */
        SourceUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Expected Cadence Hours */
            expected_cadence_hours?: number | null;
        };
        /**
         * StatusEvent
         * @description One row of the status history.
         */
        StatusEvent: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Set By */
            set_by: string | null;
            /** Status */
            status: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /**
         * SubmittedJob
         * @description Response of POST /url.
         */
        SubmittedJob: {
            /**
             * Ingestion Job Id
             * Format: uuid
             */
            ingestion_job_id: string;
        };
        /**
         * TokenResponse
         * @description A bearer token and its lifetime in seconds.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UrlSubmission
         * @description Body of POST /url.
         */
        UrlSubmission: {
            /** Case Number */
            case_number?: string | null;
            /** Circular A */
            circular_a?: string | number | null;
            /** Circular B */
            circular_b?: string | number | null;
            /** Court Code */
            court_code?: string | null;
            /** Decision Date */
            decision_date?: string | null;
            /** Doc Type */
            doc_type: string;
            /** Number */
            number?: string | number | null;
            /** Series */
            series?: string | null;
            /** Source */
            source: string;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
            /** Year */
            year?: string | number | null;
        };
        /**
         * UserCreate
         * @description Body for creating a user.
         */
        UserCreate: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Roles */
            roles: string[];
        };
        /**
         * UserItem
         * @description A user as returned by the admin API.
         */
        UserItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Login At */
            last_login_at: string | null;
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
        };
        /**
         * UserList
         * @description One page of users, newest id last.
         */
        UserList: {
            /** Items */
            items: components["schemas"]["UserItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /**
         * UserUpdate
         * @description Body for updating a user. Omitted fields are left unchanged.
         */
        UserUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Password */
            password?: string | null;
            /** Roles */
            roles?: string[] | null;
            /** Status */
            status?: ("active" | "disabled") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionOut
         * @description One version of a document.
         */
        VersionOut: {
            /** Extractor Version */
            extractor_version: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime */
            mime: string;
            /** Ocr Used */
            ocr_used: boolean;
            /** Page Count */
            page_count: number | null;
            /** Parsed At */
            parsed_at: string | null;
            /** Parser Version */
            parser_version: string | null;
            /** Segmenter Version */
            segmenter_version: string | null;
            /** Version No */
            version_no: number;
        };
        /**
         * VersionSummary
         * @description A document version as shown with a parse failure.
         */
        VersionSummary: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mime */
            mime: string;
            /** Page Count */
            page_count: number | null;
        };
        /**
         * DocumentSummary
         * @description One row of the document list.
         */
        app__routers__platform_documents__DocumentSummary: {
            /** Canonical Id */
            canonical_id: string;
            /** Current Version Id */
            current_version_id: string | null;
            /** Doc Date */
            doc_date: string | null;
            /** Doc Type */
            doc_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string | null;
            /** Review State */
            review_state: string;
            /** Series */
            series: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentSummary
         * @description The document fields a reviewer needs next to a task.
         */
        app__routers__review_tasks__DocumentSummary: {
            /** Canonical Id */
            canonical_id: string;
            /** Current Version Id */
            current_version_id: string | null;
            /** Doc Type */
            doc_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Meta Confidence */
            meta_confidence: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Review State */
            review_state: string;
            /** Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    query_audit_v1_admin_audit_get: {
        parameters: {
            query?: {
                action?: string | null;
                actor_user_id?: string | null;
                object_type?: string | null;
                object_id?: string | null;
                from_ts?: string | null;
                to_ts?: string | null;
                limit?: number;
                cursor?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    create_miss_report_v1_miss_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MissReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissReportCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_platform_documents_get: {
        parameters: {
            query?: {
                doc_type?: string | null;
                review_state?: string | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_platform_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_document_v1_platform_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_blocks_v1_platform_documents__document_id__versions__version_id__blocks_get: {
        parameters: {
            query?: {
                page?: number | null;
                /** @description Last seq of the previous page */
                after?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pages_v1_platform_documents__document_id__versions__version_id__pages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    page_image_v1_platform_documents__document_id__versions__version_id__pages__page_no__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                version_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raw_file_v1_platform_documents__document_id__versions__version_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_v1_platform_ingestion_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    get_job_v1_platform_ingestion_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_manual_v1_platform_ingestion_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_submit_manual_v1_platform_ingestion_manual_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_url_v1_platform_ingestion_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmittedJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_v1_platform_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_v1_platform_review_tasks_get: {
        parameters: {
            query?: {
                kind?: ("amendment" | "metadata" | "parse_failure" | "miss_report" | "treatment") | null;
                status?: ("open" | "in_review" | "done" | "rejected")[] | null;
                assignee?: string | null;
                source?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_v1_platform_review_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_task_v1_platform_review_tasks__task_id__assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_task_v1_platform_review_tasks__task_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewTaskUpdate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_v1_platform_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    update_source_v1_platform_sources__code__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    version_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown | null;
                    };
                };
            };
        };
    };
}
