"""Queue names for the ingestion stages (acquire and parse live in loaders.py)."""

CLASSIFY_QUEUE = "ingest.classify"
SEGMENT_QUEUE = "ingest.segment"
EXTRACT_META_QUEUE = "ingest.extract_meta"
APPLY_METADATA_QUEUE = "ingest.apply_metadata"
PUBLISH_QUEUE = "ingest.publish"
BUILD_PROVISIONS_QUEUE = "ingest.build_provisions"
AMEND_DETECT_QUEUE = "ingest.amend_detect"
CONSOLIDATE_QUEUE = "ingest.consolidate"
INDEX_QUEUE = "ingest.index"
